volumes:
  db_data:
  redis:

services:
  # db:
  #   image: postgres
  #   environment:
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_USER=root
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data
