volumes:
  db_data:

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
